openapi: 3.0.0
info:
  title: AptekON API
  version: 4.2.0
paths:
  /apteki:
    get:
      summary: Zwraca plik JSON z danymi aptek
      responses:
        200:
          description: OK
  /apteki/id:
    get:
      summary: Zwraca JSON id aptek
      responses:
        200:
          description: OK
  /uzytkownik/add:
    post:
      summary: Dodaje nowego użytkownika
      tags:
        - Użytkownicy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                haslo:
                  type: string
                admin:
                  type: number
              required:
                - email
                - haslo
      responses:
        200:
          description: Użytkownik dodany poprawnie
        400:
          description: Brak wymaganych danych
        500:
          description: Błąd serwera
 
